'use client'

import {
  Reel,
  ReelContent,
  ReelItem,
  ReelImage,
  ReelProgress,
  ReelNavigation,
  ReelHeader,
  ReelFooter,
  ReelPlayButton,
  ReelPreviousButton,
  ReelNextButton,
  type ReelItem as ReelItemType,
} from '@/components/ui/kibo-ui/reel'
import { Badge } from '@/components/ui/badge'
import { Sparkles } from 'lucide-react'

const tattooGalleryData: ReelItemType[] = [
  {
    id: '1',
    type: 'image',
    src: 'https://images.unsplash.com/photo-1565058379802-bbe93b2f703a?w=800&h=1200&fit=crop',
    duration: 5,
    alt: 'Black and gray sleeve tattoo',
    title: 'Black & Gray Realism',
    description: 'Photorealistic sleeve design with intricate shading',
  },
  {
    id: '2',
    type: 'image',
    src: 'https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?w=800&h=1200&fit=crop',
    duration: 5,
    alt: 'Colorful watercolor tattoo',
    title: 'Watercolor Style',
    description: 'Vibrant abstract watercolor back piece',
  },
  {
    id: '3',
    type: 'image',
    src: 'https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?w=800&h=1200&fit=crop',
    duration: 5,
    alt: 'Fine line geometric tattoo',
    title: 'Fine Line Work',
    description: 'Delicate geometric patterns with precise linework',
  },
  {
    id: '4',
    type: 'image',
    src: 'https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?w=800&h=1200&fit=crop',
    duration: 5,
    alt: 'Traditional Japanese tattoo',
    title: 'Japanese Traditional',
    description: 'Classic koi and waves design',
  },
  {
    id: '5',
    type: 'image',
    src: 'https://images.unsplash.com/photo-1567701554261-fcc4743c1520?w=800&h=1200&fit=crop',
    duration: 5,
    alt: 'Neo traditional rose tattoo',
    title: 'Neo Traditional',
    description: 'Bold rose with modern color palette',
  },
  {
    id: '6',
    type: 'image',
    src: 'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=800&h=1200&fit=crop',
    duration: 5,
    alt: 'Minimalist line art tattoo',
    title: 'Minimalist Design',
    description: 'Simple yet elegant line art',
  },
]

export default function TattooGallery() {
  return (
    <section className="py-20 px-4 bg-muted/30">
      <div className="container mx-auto max-w-6xl">
        <div className="text-center mb-12">
          <Badge className="mb-4" variant="secondary">
            <Sparkles className="mr-1 h-3 w-3" />
            AI-Generated Previews
          </Badge>
          <h2 className="text-3xl font-bold mb-4">Gallery of Possibilities</h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Explore tattoo previews generated by our AI. See how different styles look on real skin.
          </p>
        </div>

        <div className="flex flex-col lg:flex-row gap-8 items-center">
          {/* Reel Container */}
          <div className="mx-auto lg:mx-0">
            <div className="relative max-w-[400px] mx-auto">
              <Reel data={tattooGalleryData} autoPlay defaultMuted>
                <ReelProgress />
                <ReelContent>
                  {(item) => (
                    <ReelItem>
                      <ReelImage 
                        src={item.src} 
                        alt={item.alt || ''} 
                        duration={item.duration}
                      />
                      <ReelNavigation />
                      <ReelHeader>
                        <div className="text-white">
                          <h3 className="text-xl font-bold">{item.title}</h3>
                          <p className="text-sm opacity-90">{item.description}</p>
                        </div>
                      </ReelHeader>
                      <ReelFooter>
                        <div className="flex items-center justify-between">
                          <div className="flex gap-2">
                            <ReelPreviousButton />
                            <ReelPlayButton />
                            <ReelNextButton />
                          </div>
                          <div className="text-white text-sm">
                            <span className="opacity-75">Preview generated in</span>
                            <span className="ml-1 font-semibold">3.2s</span>
                          </div>
                        </div>
                      </ReelFooter>
                    </ReelItem>
                  )}
                </ReelContent>
              </Reel>
            </div>
          </div>

          {/* Features List */}
          <div className="flex-1 max-w-lg">
            <h3 className="text-2xl font-bold mb-6">What Our AI Can Do</h3>
            <ul className="space-y-4">
              <li className="flex items-start gap-3">
                <div className="mt-1 h-2 w-2 rounded-full bg-purple-600 shrink-0" />
                <div>
                  <h4 className="font-semibold">Realistic Skin Adaptation</h4>
                  <p className="text-sm text-muted-foreground">
                    AI adapts designs to match skin tone and body contours perfectly
                  </p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <div className="mt-1 h-2 w-2 rounded-full bg-purple-600 shrink-0" />
                <div>
                  <h4 className="font-semibold">Multiple Style Variations</h4>
                  <p className="text-sm text-muted-foreground">
                    Generate variations in different artistic styles instantly
                  </p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <div className="mt-1 h-2 w-2 rounded-full bg-purple-600 shrink-0" />
                <div>
                  <h4 className="font-semibold">Size & Placement Options</h4>
                  <p className="text-sm text-muted-foreground">
                    Test different sizes and placements before committing
                  </p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <div className="mt-1 h-2 w-2 rounded-full bg-purple-600 shrink-0" />
                <div>
                  <h4 className="font-semibold">Aging Simulation</h4>
                  <p className="text-sm text-muted-foreground">
                    Preview how tattoos will look as they age over time
                  </p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <div className="mt-1 h-2 w-2 rounded-full bg-purple-600 shrink-0" />
                <div>
                  <h4 className="font-semibold">Cover-Up Visualization</h4>
                  <p className="text-sm text-muted-foreground">
                    See how new designs will cover existing tattoos
                  </p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  )
}